_wandb:
    value:
        cli_version: 0.21.0
        e:
            apn5erf7pfhrthibosa8tagabg0y3yow:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "4294967296"
                codePath: train_vae.py
                codePathLocal: train_vae.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "414773919744"
                email: tsuberim@gmail.com
                executable: /Users/tsuberim/Projects/open-oasis/.venv/bin/python3
                git:
                    commit: 4337d5e9e88ca47dedcf5671623bc39f2ae00ef0
                    remote: git@github.com:tsuberim/open-oasis.git
                host: Matans-MacBook-Pro.local
                memory:
                    total: "25769803776"
                os: macOS-15.5-arm64-arm-64bit-Mach-O
                program: /Users/tsuberim/Projects/open-oasis/train_vae.py
                python: CPython 3.13.5
                root: /Users/tsuberim/Projects/open-oasis
                startedAt: "2025-07-26T15:27:53.689427Z"
                writerId: apn5erf7pfhrthibosa8tagabg0y3yow
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
            "2":
                - 1
                - 41
                - 49
                - 63
            "3":
                - 13
                - 16
            "4": 3.13.5
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
batch_size:
    value: 8
epochs:
    value: 100
lr:
    value: 0.0001
seed:
    value: 42
target_size:
    value:
        - 360
        - 640
test_ratio:
    value: 0.15
